config {
    type: "view",
    name: "source_view",
    description: "Description of the table",
    assertions: {
        uniqueKey: ["fruit"],
        rowConditions: [
            'count > 5'
        ]
    }

}

SELECT
  "apples" AS fruit,
  3 AS count
UNION ALL
SELECT
  "oranges" AS fruit,
  5 AS count
UNION ALL
SELECT
  "pears" AS fruit,
  1 AS count
UNION ALL
SELECT
  "bananas" AS fruit,
  0 AS count
